### ISSUE TITLE
Migrate to from database to declarative index

### ISSUE THREAD

**Issue by rtclauss** [IBMStockTrader/stocktrader-operator#17]
The existing operator uses a database for the index.

If you attempt to install the StockTrader operator on a cluster that has an OLM version of greater than `v0.21.1` you will see failures when deploying the operator and you will see this in the logs somewhere:
```
Sqlite-based catalogs and their related subcommands are deprecated. Support for
them will be removed in a future release. Please migrate your catalog workflows
to the new file-based catalog format.
```

A workaround is to install version `v0.21.1`of OLM in your cluster:
```bash
operator-sdk olm install --version=v0.21.1
```

I believe this means we need to move to the declarative-style of operator index.

https://github.com/operator-framework/enhancements/blob/master/enhancements/declarative-index-config.md#deprecations
https://github.com/operator-framework/olm-docs/pull/177
https://olm.operatorframework.io/docs/reference/file-based-catalogs/

**Comment by jwalcorn** [comment]
I made this move several months ago.  See the bundle/README.md for details.  Let me know if there's still any issue.  Thanks.
