### ISSUE TITLE
Adding encryption configuration properties for stock quote

### ISSUE THREAD

**Issue by sigfrido45** [IBMStockTrader/stocktrader-operator#18]
First ```encryptorType``` field, in stock-quote-spring we have 4 types of encryptors:
1. springSecurityBytesEncryptor -> using Spring Security bytes encryptor method
2. noneEncryptor -> Not using encryption
3. aesGsmEncryptor -> Galois Counter mode encryptor
4. springSecurityTextEncryptor -> using Spring Security text encryptor method

```saltBytes```  property, which is generated by ```KeyGenerators.string().generateKey()```,  it allows to work with multiple replicas of stock-quote which can decrypt and encrypt simulteanosly

Finally ```encryptionPassword``` property used for encryption and decryption.

**Comment by jwalcorn** [comment]
Addressed in v1.0.0 of the operator
