### ISSUE TITLE
Add two new cloudant/couchdb fields

### ISSUE THREAD

**Issue by rtclauss** [IBMStockTrader/stocktrader-operator#36]
As part of the JNoSQL and pagination work we have the need for new environment variables and the chance to remove one.

The dependent PRs' are: 
* https://github.com/IBMStockTrader/broker/pull/10
* https://github.com/IBMStockTrader/account/pull/12

The environment variables to add are:
1. `CLOUDANT_HOST`
2. `CLOUDANT_PORT` 

And remove:
* `CLOUDANT_URL` - this is [used by](https://github.com/search?q=org%3AIBMStockTrader%20CLOUDANT_URL&type=code) both `account` and `collector` but we really don't use `collector` anymore.

A side discussion that is very relevant: Should we rename the variables to be `COUCHDB_` prefixed vs. `CLOUDANT_` @jwalcorn ?

**Comment by jwalcorn** [comment]
Done
